-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 09:50:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfirst` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vlucht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vlucht` (
  `vluchtnummer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vliegtuig_type` VARCHAR(45) NOT NULL,
  `vertrek_vluchthaven` VARCHAR(45) NOT NULL,
  `aankomst_vlucht_haven` VARCHAR(45) NOT NULL,
  `vertrektijd` VARCHAR(45) NOT NULL,
  `aankomst_tijd` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`vluchtnummer`),
  UNIQUE INDEX `vluchtnummer_UNIQUE` (`vluchtnummer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personeel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personeel` (
  `naam` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`naam`),
  UNIQUE INDEX `naam_UNIQUE` (`naam` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vlucht_has_Personeel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vlucht_has_Personeel` (
  `Vlucht_vluchtnummer` INT UNSIGNED NOT NULL,
  `Personeel_naam` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Vlucht_vluchtnummer`, `Personeel_naam`),
  INDEX `fk_Vlucht_has_Personeel_Personeel1_idx` (`Personeel_naam` ASC) VISIBLE,
  INDEX `fk_Vlucht_has_Personeel_Vlucht_idx` (`Vlucht_vluchtnummer` ASC) VISIBLE,
  CONSTRAINT `fk_Vlucht_has_Personeel_Vlucht`
    FOREIGN KEY (`Vlucht_vluchtnummer`)
    REFERENCES `mydb`.`Vlucht` (`vluchtnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vlucht_has_Personeel_Personeel1`
    FOREIGN KEY (`Personeel_naam`)
    REFERENCES `mydb`.`Personeel` (`naam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dbfirst` ;

-- -----------------------------------------------------
-- Table `dbfirst`.`bordspellen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`bordspellen` (
  `idbordspellen` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(250) NOT NULL,
  `aantal spelers` INT NOT NULL,
  `beschrijving` VARCHAR(500) NOT NULL,
  `coop` INT NOT NULL,
  PRIMARY KEY (`idbordspellen`),
  UNIQUE INDEX `idbordspellen_UNIQUE` (`idbordspellen` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
